# -*- coding: utf-8 -*-
"""Day 5: Normal Distribution I .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kaH9M3V_wYjsZ4x2xsEzKl03JcTze3Og
"""

import math
def cdf(x, mean, std):
    return 1/2*(1+math.erf((x-mean) / std / 2**(1/2)))
mean = 20
std = 2
print(round(cdf(19.5, mean, std), 3))
print(round(cdf(22, mean, std) - cdf(20, mean, std), 3))