# -*- coding: utf-8 -*-
"""Day 6: The Central Limit Theorem III.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kaH9M3V_wYjsZ4x2xsEzKl03JcTze3Og
"""

mean = 500
std = 80
n = 100
z = 1.96
mean = mean
std = std / n**(1/2)
print(round(mean - std * z, 2))
print(round(mean + std * z, 2))