# -*- coding: utf-8 -*-
"""Day 4: Binomial Distribution .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kaH9M3V_wYjsZ4x2xsEzKl03JcTze3Og
"""

import math
p = 1.09/(1+1.09)
ans = 0
for i in range(3):
    ans += math.factorial(6) / math.factorial(i) / math.factorial(6-i) * p**i * (1-p)**(6-i)
print(round(1-ans, 3))