# -*- coding: utf-8 -*-
"""Day 5: Normal Distribution II .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kaH9M3V_wYjsZ4x2xsEzKl03JcTze3Og
"""

import math
def cdf(x, mean, std):
    return 1/2*(1+math.erf((x-mean) / std / 2**(1/2)))
mean = 70
std = 10
print(round((1 - cdf(80, mean, std))*100, 2))
print(round((1 - cdf(60, mean, std))*100, 2))
print(round(cdf(60, mean, std)*100, 2))