# -*- coding: utf-8 -*-
"""Arithmetic Operators.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rcddYS055QEKVhLDMjs1wBYHBbZ5kBFZ
"""

a = int(input())
b = int(input())

print(a+b)
print(a-b)
print(a*b)