# -*- coding: utf-8 -*-
"""loops.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rcddYS055QEKVhLDMjs1wBYHBbZ5kBFZ
"""

n = int(input())

for i in range(0,n) :
    print( i*i)