# -*- coding: utf-8 -*-
"""print("Hello, World!").ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k4AZnBCpYS5WdhF_o8wbbK2OBhoHpL2S
"""

print("Hello, World!")