# -*- coding: utf-8 -*-
"""Print Function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rcddYS055QEKVhLDMjs1wBYHBbZ5kBFZ
"""

n = int(input())
for i in range(1,n+1):
        print(i,end="")

is_leap(2016)