# -*- coding: utf-8 -*-
"""String Split and Join.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TZa_H5ZsZgY-czIJZrit-XPL46IeUla7
"""

def split_and_join(line):
    a = line.split(" ")
    a = "-".join(a)
    return a
    line = input()
    result = split_and_join(line)
    print(result)