# -*- coding: utf-8 -*-
"""sWAP cASE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TZa_H5ZsZgY-czIJZrit-XPL46IeUla7
"""

s = input()
def swap_case(s):
    return s.swapcase()
result = swap_case(s)
print(result)