# -*- coding: utf-8 -*-
"""What's Your Name?.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TZa_H5ZsZgY-czIJZrit-XPL46IeUla7
"""

def print_full_name(first, last):
    print("Hello "+first+" "+last+"! You just delved into python.")

print_full_name("aman","s")

