# -*- coding: utf-8 -*-
"""Find the Runner-Up Score!.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TZa_H5ZsZgY-czIJZrit-XPL46IeUla7
"""

n = int(input())
arr = map(int, input().split())
print(sorted(list(set(arr)))[-2])