# -*- coding: utf-8 -*-
"""List Comprehensions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SVoR--NOZGwLB69yLE51CeLYQLSnCsTh
"""

x = int(input())
y = int(input())
z = int(input())
n = int(input())
output = [];
abc = [];
for X in range(x+1):
  for Y in range(y+1):
      for Z in range(z+1):
        if X+Y+Z != n:
          abc = [X,Y,Z];
        output.append(abc);
print(output);