# -*- coding: utf-8 -*-
"""Tuples.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TZa_H5ZsZgY-czIJZrit-XPL46IeUla7
"""

n =int(input())
integer_list = map(int, input().split())
print(hash(tuple(integer_list)))