# -*- coding: utf-8 -*-
"""Array Mathematics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kaH9M3V_wYjsZ4x2xsEzKl03JcTze3Og
"""

import numpy
numpy.set_printoptions(sign=' ')
array = numpy.array(input().split(),float)
print(numpy.floor(array))
print(numpy.ceil(array))
print(numpy.rint(array))