# -*- coding: utf-8 -*-
"""Eye and Identity.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kaH9M3V_wYjsZ4x2xsEzKl03JcTze3Og
"""

import numpy
numpy.set_printoptions(sign=' ')
print(numpy.eye(*map(int, input().split())))