# -*- coding: utf-8 -*-
"""Inner and Outer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kaH9M3V_wYjsZ4x2xsEzKl03JcTze3Og
"""

import numpy
A = numpy.array(input().split(), int)
B = numpy.array(input().split(), int)
print(numpy.inner(A, B), numpy.outer(A, B), sep='\n')