# -*- coding: utf-8 -*-
"""Shape and Reshape.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kaH9M3V_wYjsZ4x2xsEzKl03JcTze3Og
"""

import numpy
print(numpy.array(input().split(), int).reshape(3, 3))