# -*- coding: utf-8 -*-
"""Group(), Groups() & Groupdict().ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kaH9M3V_wYjsZ4x2xsEzKl03JcTze3Og
"""

import re
expression=r"([a-zA-Z0-9])\1+"
m = re.search(expression,input())
if m:
    print(m.group(1))
else:
    print(-1)