# -*- coding: utf-8 -*-
"""Re.split().ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kaH9M3V_wYjsZ4x2xsEzKl03JcTze3Og
"""

regex_pattern = r""	# Do not delete 'r'.
regex_pattern = r"[.,]+"
import re
print("\n".join(re.split(regex_pattern, input())))