# -*- coding: utf-8 -*-
"""Re.start() & Re.end().ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kaH9M3V_wYjsZ4x2xsEzKl03JcTze3Og
"""

import re
string = input()
substring = input()
pattern = re.compile(substring)
match = pattern.search(string)
if not match: 
    print('(-1, -1)')
while match:
    print('({0}, {1})'.format(match.start(), match.end() - 1))
    match = pattern.search(string, match.start() + 1)