# -*- coding: utf-8 -*-
"""Regex Substitution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kaH9M3V_wYjsZ4x2xsEzKl03JcTze3Og
"""

import re
def change(match):
    if match.group(1) == '&&':
        return 'and'
    else:
        return 'or'
for _ in range(int(input())):
    print(re.sub(r"(?<= )(\|\||&&)(?= )", change,input()))