# -*- coding: utf-8 -*-
"""Find Angle MBC .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SVoR--NOZGwLB69yLE51CeLYQLSnCsTh
"""

import math
from math import sqrt
ab=int(input())
bc=int(input())
ac=math.hypot(ab,bc)
mc=ac/2
bca=math.asin(1*ab/ac)
bm=math.sqrt((bc**2+mc**2)-(2*bc*mc*math.cos(bca)))
mbc=math.asin(math.sin(bca)*mc/bm)
print(int(round(math.degrees(mbc),0)),'\u00B0',sep='')