# -*- coding: utf-8 -*-
"""Integers Come In All Sizes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SVoR--NOZGwLB69yLE51CeLYQLSnCsTh
"""

a=int(input())
b=int(input())
c=int(input())
d=int(input())
print(pow(a,b)+pow(c,d))2