# -*- coding: utf-8 -*-
"""Mod_Divmod.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TZa_H5ZsZgY-czIJZrit-XPL46IeUla7
"""

a=int(input())
b=int(input())
print(a//b)
print(a%b)
print(divmod(a,b))