# -*- coding: utf-8 -*-
"""Polar Coordinates .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SVoR--NOZGwLB69yLE51CeLYQLSnCsTh
"""

import cmath
z = input()
print(abs(complex(z)))
print(cmath.phase(complex(z)))