# -*- coding: utf-8 -*-
"""Power - Mod Power.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SVoR--NOZGwLB69yLE51CeLYQLSnCsTh
"""

a=int(input())
b=int(input())
m=int(input())
print(pow(a,b))
print(pow(a,b,m))