# -*- coding: utf-8 -*-
"""Triangle Quest 2 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SVoR--NOZGwLB69yLE51CeLYQLSnCsTh
"""

for i in range(1,int(input())+1):
     print(((10**i)//9)**2)