# -*- coding: utf-8 -*-
"""Task - 7 (Descriptive Stats - Both basic and Adv Users).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kaH9M3V_wYjsZ4x2xsEzKl03JcTze3Og

loading dataset
"""

import numpy as np
import pandas as pd
data=pd.read_csv("/data (2).csv")

"""MEAN"""

data.head()

data.mean(axis = 0)

"""Median"""

data.median(axis = 0)

"""mode

"""

data.mode(axis = 0)

"""Variance"""

data.var(axis = 0)

"""Standard Deviation"""

data.std(axis = 0)

"""Correlation

"""

data.corr(method ='kendall')

"""Normal Distribution"""

import matplotlib.pyplot as plt
from scipy.stats import norm
import statistics  
mean = statistics.mean(data["Mthly_HH_Income"])
sd = statistics.stdev(data["Mthly_HH_Income"])
  
plt.plot(data["Mthly_HH_Income"], norm.pdf(data["Mthly_HH_Income"], mean, sd))
plt.show()